### ISSUE TITLE
Selected pages are not showing up

### ISSUE THREAD

**Issue by eriksachse** [sylvainjule/kirby-bouncer#20]
My setup:

- content
  - 1_class1
    - 1_student-a
      - student.txt
    - 2_student-b
      - student.txt

- site
  - blueprints
    - users
      - student.yml

This is the student.yml file:
```
title: Student

permissions:
  access:
    panel: true
    site: true
    settings: false
    languages: false
    users: false
  # ...
  user:
    changeRole: false
    delete: false
    update: false # else a user will be able to edit the page they have access to on their profile

fields:
  canaccess:
    label: "The user will only be able to access:"
    type: pages
    options: query
    query: site.pages
```

Unfortunately it shows _No pages selected yet_ in the pages view. I tried multiple query methods, but it never worked for me. 
How can I add pages to the query?
